// Fragment parsing: front matter → Fragment values, slug derivation, and
// the per-file lint rules (L100–L110) that fire during parsing.
import { test } from "node:test";
import assert from "node:assert/strict";

import { parseFragment, slugFromFile } from "../dist/fragment.js";

function parse(source, file = ".rulecast/sample.md", slug = "sample") {
  return parseFragment(file, slug, source);
}

function codes(source) {
  return parse(source).diagnostics.map((d) => d.code);
}

test("slugFromFile: basename minus .md, lowercased, punctuation collapsed", () => {
  assert.equal(slugFromFile("Web TypeScript.md"), "web-typescript");
  assert.equal(slugFromFile("nested/dir/00-project.md"), "00-project");
  assert.equal(slugFromFile("API_Style.md"), "api-style");
});

test("a complete fragment parses with every field populated", () => {
  const { fragment, diagnostics } = parse(
    '---\ntitle: Web rules\ndescription: TS conventions\nscope: packages/web/**\ntargets: [claude, cursor]\norder: 20\n---\n\n- Use strict mode.\n',
  );
  assert.deepEqual(diagnostics, []);
  assert.equal(fragment.title, "Web rules");
  assert.equal(fragment.description, "TS conventions");
  assert.equal(fragment.scope, "packages/web/**");
  assert.deepEqual(fragment.targets, ["claude", "cursor"]);
  assert.equal(fragment.order, 20);
  assert.equal(fragment.body, "- Use strict mode.");
});

test('defaults: targets null, order 100, and scope "**" normalizes to repo-wide', () => {
  const { fragment } = parse("---\ntitle: T\n---\nbody");
  assert.equal(fragment.targets, null);
  assert.equal(fragment.order, 100);
  assert.equal(fragment.scope, undefined);

  const starred = parse('---\ntitle: T\nscope: "**"\n---\nbody');
  assert.equal(starred.fragment.scope, undefined);
});

test("body is trimmed of surrounding blank lines but kept verbatim inside", () => {
  const { fragment } = parse("---\ntitle: T\n---\n\n\n- a\n\n- b\n\n\n");
  assert.equal(fragment.body, "- a\n\n- b");

  // CRLF sources normalize to LF: a Windows-authored fragment must compile
  // to the same bytes as a Unix one, or `check` reports phantom drift.
  const crlf = parse("---\r\ntitle: T\r\n---\r\n\r\n- a\r\n\r\n- b\r\n");
  assert.equal(crlf.fragment.title, "T");
  assert.equal(crlf.fragment.body, "- a\n\n- b");
});

test("L100: broken front matter yields no fragment and one error", () => {
  const { fragment, diagnostics } = parse("---\ntitle: T\nno closing");
  assert.equal(fragment, null);
  assert.deepEqual(diagnostics.map((d) => d.code), ["L100"]);
});

test("L101: missing title is an error", () => {
  const result = parse("---\norder: 5\n---\nbody");
  assert.equal(result.fragment, null);
  assert.equal(result.diagnostics.find((d) => d.code === "L101").severity, "error");
});

test("L102 and L110: empty bodies and marker text in bodies are errors", () => {
  assert.ok(codes("---\ntitle: T\n---\n\n").includes("L102"));
  assert.ok(codes("---\ntitle: T\n---\nsays Generated by rulecast inside").includes("L110"));
});

test("L103: unknown or non-array targets are errors", () => {
  const diagnostics = parse("---\ntitle: T\ntargets: [claude, vscode, zed]\n---\nbody").diagnostics;
  assert.equal(diagnostics.filter((d) => d.code === "L103").length, 2, "one per bad entry");
  assert.ok(codes("---\ntitle: T\ntargets: claude\n---\nbody").includes("L103"));
});

test("L104: invalid scope carries the validator's reason, anchored to its line", () => {
  const diagnostics = parse("---\ntitle: T\nscope: /abs/**\norder: nope\n---\nbody").diagnostics;
  const l104 = diagnostics.find((d) => d.code === "L104");
  assert.match(l104.message, /repo-relative/);
  assert.equal(l104.line, 3);
  assert.equal(diagnostics.find((d) => d.code === "L107").line, 4);
});

test("L105: unknown keys warn but do not block the fragment", () => {
  const { fragment, diagnostics } = parse("---\ntitle: T\ncolour: blue\n---\nbody");
  assert.notEqual(fragment, null);
  const l105 = diagnostics.find((d) => d.code === "L105");
  assert.equal(l105.severity, "warning");
  assert.match(l105.message, /colour/);
});

test("L107 and L109: bad order, and a targets list that selects nothing", () => {
  assert.ok(codes("---\ntitle: T\norder: first\n---\nbody").includes("L107"));
  assert.ok(codes("---\ntitle: T\ntargets: []\n---\nbody").includes("L109"));
});

test("duplicate targets are de-duplicated without a diagnostic", () => {
  const { fragment, diagnostics } = parse("---\ntitle: T\ntargets: [claude, claude]\n---\nbody");
  assert.deepEqual(fragment.targets, ["claude"]);
  assert.deepEqual(diagnostics, []);
});
