/**
 * Drift detection — the heart of `rulecast check` and the dry-run side of
 * `build`. Given the compiled plan and a view of the working tree, report
 * every way the tree disagrees with the plan:
 *
 *  - missing    a planned file is absent
 *  - stale      a planned file exists but its content differs
 *  - unmanaged  a planned path is occupied by a file without the marker
 *               (build will not overwrite it without --force)
 *  - orphaned   a marker-bearing file no fragment produces anymore
 *
 * Pure functions over values; the filesystem view is injected.
 */

import { isManaged } from "./marker.js";
import type { DriftFinding, PlannedFile } from "./types.js";

/** A minimal read-only view of the repo, injectable in tests. */
export interface TreeView {
  /** File content, or null when the path does not exist. */
  read(relPath: string): string | null;
  /** Marker-scan candidates: existing files that could be rulecast output. */
  candidates(): string[];
}

/** Compare the plan against the tree and list every disagreement. */
export function diffPlan(plan: PlannedFile[], tree: TreeView): DriftFinding[] {
  const findings: DriftFinding[] = [];
  const plannedPaths = new Set(plan.map((p) => p.path));

  for (const file of plan) {
    const onDisk = tree.read(file.path);
    if (onDisk === null) {
      findings.push({
        kind: "missing",
        path: file.path,
        target: file.target,
        detail: "planned but absent — run `rulecast build`",
      });
    } else if (!isManaged(onDisk)) {
      findings.push({
        kind: "unmanaged",
        path: file.path,
        target: file.target,
        detail: "exists but has no rulecast marker — `rulecast build --force` will replace it",
      });
    } else if (onDisk !== file.content) {
      findings.push({
        kind: "stale",
        path: file.path,
        target: file.target,
        detail: "content differs from the compiled fragments — run `rulecast build`",
      });
    }
  }

  // Orphans: files that identify themselves as rulecast output but that the
  // current fragments no longer produce (fragment deleted, scope moved,
  // target disabled). Sorted for stable reporting.
  for (const path of [...tree.candidates()].sort()) {
    if (plannedPaths.has(path)) continue;
    const content = tree.read(path);
    if (content !== null && isManaged(content)) {
      findings.push({
        kind: "orphaned",
        path,
        detail: "generated by rulecast but no fragment produces it — run `rulecast build --prune`",
      });
    }
  }

  return findings;
}

/** True when the tree fully matches the plan (check exits 0). */
export function isClean(findings: DriftFinding[]): boolean {
  return findings.length === 0;
}
