/**
 * The generated-file marker. Every file rulecast writes carries one HTML
 * comment containing MARKER_TOKEN; that token is the sole test for "is this
 * file managed by rulecast". `build` refuses to overwrite files without it
 * (protecting a hand-written CLAUDE.md from being clobbered), and `check`
 * uses it to spot orphans whose fragments have since been deleted.
 */

/** Substring whose presence marks a file as rulecast-managed. */
export const MARKER_TOKEN = "Generated by rulecast";

/** How many leading bytes of a file are searched for the token. */
export const MARKER_SCAN_BYTES = 512;

/** The full marker comment written into generated files. */
export function markerComment(sourceDir: string): string {
  return `<!-- ${MARKER_TOKEN} from ${sourceDir}/ — do not edit by hand. Edit the fragments, then run \`rulecast build\`. -->`;
}

/** True when the file content identifies itself as rulecast output. */
export function isManaged(content: string): boolean {
  return content.slice(0, MARKER_SCAN_BYTES).includes(MARKER_TOKEN);
}
